package com.cj.asr.entity;

import javax.persistence.*;
import java.io.Serializable;
import java.sql.Timestamp;

import lombok.Data;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

/**
 * generated by Generate MyPOJOs.groovy 
 * <p>Date: Thu Mar 28 16:53:06 CST 2019.</p>
 *
 * @author Flon
 */
@Data
@Entity
@Table ( name ="cj_voice_text_role_result_emo" )
@EntityListeners(AuditingEntityListener.class)
public class VoiceTextRoleResultEmo  implements Serializable {


	private static final long serialVersionUID =  9207247296741819370L;


	/**
	 * id
	 */
   	@Column(name = "id", columnDefinition = "id" )	@Id	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer id;

	@CreatedDate
   	@Column(name = "creation_time",updatable = false, columnDefinition = "null" )
	private Timestamp creationTime;

	/**
	 * 开始时间
	 */
   	@Column(name = "begin_time", columnDefinition = "开始时间" )
	private String beginTime;

	/**
	 * 结束时间
	 */
   	@Column(name = "end_time", columnDefinition = "结束时间" )
	private String endTime;

	/**
	 * 全文内容
	 */
   	@Column(name = "content", columnDefinition = "全文内容" )
	private String content;

	/**
	 * 角色（0：客户，1：坐席）
	 */
   	@Column(name = "role", columnDefinition = "角色（1：客户，2：坐席）" )
	private Integer role;

	/**
	 * 性别,1:男，0:女
	 */
   	@Column(name = "gender", columnDefinition = "性别,1:男，0:女" )
	private Integer gender;

	/**
	 * 情绪（neu中性 happy高兴 angry生气）
	 */
   	@Column(name = "emotion", columnDefinition = "情绪（neu中性 happy高兴 angry生气）" )
	private String emotion;

	/**
	 * 置信度
	 */
   	@Column(name = "credible", columnDefinition = "置信度" )
	private String credible;

	/**
	 * 声调值0.0-1.0，在原来的基础上，声调增加值
	 */
   	@Column(name = "tone_value", columnDefinition = "声调值0.0-1.0，在原来的基础上，声调增加值" )
	private String toneValue;

	/**
	 * 情绪波动的开始时间
	 */
   	@Column(name = "tone_begin_time", columnDefinition = "情绪波动的开始时间" )
	private String toneBeginTime;

	/**
	 * 情绪波动的结束时间
	 */
   	@Column(name = "tone_end_time", columnDefinition = "情绪波动的结束时间" )
	private String toneEndTime;

	/**
	 * 音频标识
	 */
   	@Column(name = "audio_id", columnDefinition = "音频标识" )
	private Integer audioId;

	/**
	 * 音频文件名
	 */
   	@Column(name = "audio_name", columnDefinition = "音频文件名" )
	private String audioName;

}
