package com.cj.asr.entity;

import javax.persistence.*;
import java.io.Serializable;
import java.sql.Timestamp;

import lombok.Data;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

/**
 * generated by Generate MyPOJOs.groovy 
 * <p>Date: Thu Mar 28 16:53:06 CST 2019.</p>
 *
 * @author Flon
 */
@Data
@Entity
@Table ( name ="cj_voice_text_role_speed_result" )
@EntityListeners(AuditingEntityListener.class)
public class VoiceTextRoleSpeedResult  implements Serializable {


	private static final long serialVersionUID =  7622973966562017795L;


	/**
	 * id
	 */
   	@Column(name = "id", columnDefinition = "id" )	@Id	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer id;

	@CreatedDate
   	@Column(name = "creation_time",updatable = false, columnDefinition = "null" )
	private Timestamp creationTime;

	/**
	 * 开始时间
	 */
   	@Column(name = "begin_time", columnDefinition = "开始时间" )
	private String beginTime;

	/**
	 * 结束时间
	 */
   	@Column(name = "end_time", columnDefinition = "结束时间" )
	private String endTime;

	/**
	 * 语音转写文本
	 */
   	@Column(name = "content", columnDefinition = "语音转写文本" )
	private String content;

	/**
	 * 角色（0：客户，1：坐席）
	 */
   	@Column(name = "role", columnDefinition = "角色（1：客户，2：坐席）" )
	private Integer role;

	/**
	 * 语速，单位：字/秒，公式：字数/(结束时间-开始时间)

	 */
   	@Column(name = "speed", columnDefinition = "语速，单位：字/秒，公式：字数/(结束时间-开始时间) " )
	private String speed;

	/**
	 * 音频标识
	 */
   	@Column(name = "audio_id", columnDefinition = "音频标识" )
	private Integer audioId;

	/**
	 * 音频文件名
	 */
   	@Column(name = "audio_name", columnDefinition = "音频文件名" )
	private String audioName;

}
