package com.cj.asr.entity;

import javax.persistence.*;
import java.io.Serializable;
import lombok.Data;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

/**
 * generated by Generate MyPOJOs.groovy 
 * <p>Date: Sat Mar 30 00:42:04 CST 2019.</p>
 *
 * @author Flon
 */
@Data
@Entity
@Table ( name ="cj_voice_text_role_speed_average" )
@EntityListeners(AuditingEntityListener.class)
public class VoiceTextRoleSpeedAverage  implements Serializable {


	private static final long serialVersionUID =  8237462822711001364L;


	/**
	 * id
	 */
   	@Column(name = "id", columnDefinition = "id" )	@Id	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer id;

   	@CreatedDate
   	@Column(name = "create_time", columnDefinition = "null" )
	private java.sql.Timestamp createTime;

	/**
	 * 音频文件名
	 */
   	@Column(name = "audio_name", columnDefinition = "音频文件名" )
	private String audioName;

	/**
	 * 客服平均语速
	 */
   	@Column(name = "speed_service", columnDefinition = "客服平均语速" )
	private Double speedService;

	/**
	 * 客户平均语速
	 */
   	@Column(name = "speed_client", columnDefinition = "客户平均语速" )
	private Double speedClient;

	/**
	 * 整体平均语速
	 */
   	@Column(name = "speed_mix", columnDefinition = "整体平均语速" )
	private Double speedMix;

}
