package com.cj.asr.entity;

import javax.persistence.*;
import java.io.Serializable;
import java.sql.Timestamp;

import lombok.Data;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;;

/**
 * generated by Generate MyPOJOs.groovy 
 * <p>Date: Thu Mar 28 16:53:06 CST 2019.</p>
 *
 * @author Flon
 */
@Data
@Entity
@Table ( name ="cj_voice_emotion_result_detail" )
@EntityListeners(AuditingEntityListener.class)
public class VoiceEmotionResultDetail  implements Serializable {


	private static final long serialVersionUID =  7873102569701338724L;


	/**
	 * id
	 */
   	@Column(name = "id", columnDefinition = "id" )	@Id	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer id;

   	@CreatedDate
   	@Column(name = "creation_time",updatable = false, columnDefinition = "null" )
	private Timestamp creationTime;

	/**
	 * 情绪识别结果
	 */
   	@Column(name = "result", columnDefinition = "情绪识别结果" )
	private String result;

	/**
	 * 开始时间
	 */
   	@Column(name = "begin_time", columnDefinition = "开始时间" )
	private String beginTime;

	/**
	 * 结束时间
	 */
   	@Column(name = "end_time", columnDefinition = "结束时间" )
	private String endTime;

	/**
	 * 置信度
	 */
   	@Column(name = "credible", columnDefinition = "置信度" )
	private String credible;

	/**
	 * 角色（0：客户，1：坐席）
	 */
   	@Column(name = "role", columnDefinition = "角色（1：客户，2：坐席）" )
	private Integer role;

	/**
	 * 性别,1:男，0:女
	 */
   	@Column(name = "gender", columnDefinition = "性别,1:男，0:女" )
	private Integer gender;

	/**
	 * 音频id
	 */
   	@Column(name = "audio_id", columnDefinition = "音频id" )
	private Integer audioId;

	/**
	 * 音频文件名
	 */
   	@Column(name = "audio_name", columnDefinition = "音频文件名" )
	private String audioName;

}
